ALTER TABLE TransPackageContent DROP FOREIGN KEY FKTransPacka696996;
ALTER TABLE TransPackageContent DROP FOREIGN KEY FKTransPacka501479;
ALTER TABLE TransHistory DROP FOREIGN KEY FKTransHisto601520;
ALTER TABLE ExpressSheet DROP FOREIGN KEY FKExpressShe115006;
ALTER TABLE ExpressSheet DROP FOREIGN KEY FKExpressShe199945;
DROP TABLE IF EXISTS TransNode;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS CustomerInfo;
DROP TABLE IF EXISTS Position;
DROP TABLE IF EXISTS TransPackageContent;
DROP TABLE IF EXISTS TransHistory;
DROP TABLE IF EXISTS TransPackage;
DROP TABLE IF EXISTS ExpressSheet;
CREATE TABLE TransNode (ID char(8) NOT NULL, NodeName varchar(32), NodeType int(10) NOT NULL, RegionCode varchar(6), PostCode int(10), TelCode varchar(24) NOT NULL, PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE Region (RegionCode char(6) NOT NULL, Prv varchar(32), Cty varchar(32), Twn varchar(32), Stage int(4) NOT NULL, PRIMARY KEY (RegionCode)) CHARACTER SET UTF8;
CREATE TABLE UserInfo (UID int(10) NOT NULL AUTO_INCREMENT, PWD varchar(8), Name varchar(16), URull int(4) NOT NULL, TelCode varchar(24) NOT NULL, Status int(4) NOT NULL, DptID char(8), ReceivePackageID char(24), DelivePackageID char(24), TransPackageID char(24), PRIMARY KEY (UID)) CHARACTER SET UTF8;
CREATE TABLE CustomerInfo (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(16), TelCode varchar(24), Department varchar(64), RegionCode char(6), Address varchar(64), PostCode int(10) NOT NULL, PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE Position (PosCode int(10) NOT NULL AUTO_INCREMENT, X float NOT NULL, Y float NOT NULL, PRIMARY KEY (PosCode)) CHARACTER SET UTF8;
CREATE TABLE TransPackageContent (SN int(11) NOT NULL AUTO_INCREMENT, ExpressSheetID char(24) NOT NULL, TransPackageID char(24) NOT NULL, PRIMARY KEY (SN)) CHARACTER SET UTF8;
CREATE TABLE TransHistory (SN int(11) NOT NULL AUTO_INCREMENT, PackegID char(24) NOT NULL, ActTime datetime NOT NULL, PosCode int(10), UIDFrom int(10) NOT NULL, UIDTo int(10) NOT NULL, PRIMARY KEY (SN)) CHARACTER SET UTF8;
CREATE TABLE TransPackage (ID char(24) NOT NULL, SourceNode char(8), TargetNode char(8), CreateTime datetime NULL, Status int(4) NOT NULL, PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE ExpressSheet (ID char(24) NOT NULL, Type int(4) NOT NULL, Sender int(10), Recever int(10), Weight float, TranFee float, PackageFee float, InsuFee float, Accepter varchar(16), Deliver varchar(16), AccepteTime datetime NULL, DeliveTime datetime NULL, Acc1 varchar(64), Acc2 varchar(64), Status int(4), PRIMARY KEY (ID)) CHARACTER SET UTF8;
ALTER TABLE TransPackageContent ADD INDEX FKTransPacka696996 (ExpressSheetID), ADD CONSTRAINT FKTransPacka696996 FOREIGN KEY (ExpressSheetID) REFERENCES ExpressSheet (ID);
ALTER TABLE TransPackageContent ADD INDEX FKTransPacka501479 (TransPackageID), ADD CONSTRAINT FKTransPacka501479 FOREIGN KEY (TransPackageID) REFERENCES TransPackage (ID);
ALTER TABLE TransHistory ADD INDEX FKTransHisto601520 (PackegID), ADD CONSTRAINT FKTransHisto601520 FOREIGN KEY (PackegID) REFERENCES TransPackage (ID);
ALTER TABLE ExpressSheet ADD INDEX FKExpressShe115006 (Sender), ADD CONSTRAINT FKExpressShe115006 FOREIGN KEY (Sender) REFERENCES CustomerInfo (ID);
ALTER TABLE ExpressSheet ADD INDEX FKExpressShe199945 (Recever), ADD CONSTRAINT FKExpressShe199945 FOREIGN KEY (Recever) REFERENCES CustomerInfo (ID);
